image: registry.secoder.net/tool/deployer

stages:
  - build
  - test

cache:
  key: master
  paths:
    - node_modules/
    - .gradle/caches/
    - .gradle/wrapper/

android-build:
  image: reactnativecommunity/react-native-android
  stage: build
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - npm config set registry https://registry.npm.taobao.org
    - yarn
  script:
    - cd android && chmod +x gradlew && ./gradlew assembleRelease && cd ..
  after_script:
    - mkdir outputs
    - mv android/app/build/outputs/apk/release/app-release.apk outputs/door-lock-release.apk
    - rm -f  .gradle/caches/modules-2/modules-2.lock
    - rm -fr .gradle/caches/*/plugin-resolution/
  artifacts:
    paths:
      - outputs/

.test:
  image: reactnativecommunity/react-native-android
  stage: test
  before_script:
    - npm config set registry https://registry.npm.taobao.org
    - yarn

unit-test:
  extends: .test
  script:
    - yarn test
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://10.0.0.11/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

style-test:
  extends: .test
  script:
    - yarn lint
