language: objective-c
os: osx
osx_image: xcode12
podfile: ios/Podfile
cache:
  - yarn
  - cocoapods
before_install:
  - nvm install node
  - npm install -g yarn
install:
  - brew tap wix/brew
  - brew install applesimutils
  - gem install fastlane
  - gem install cocoapods
  - yarn
  - cd ios && pod install && cd ..
script:
  - yarn ios
